# AquesTalk1's macOS dylibs are arm64-only. AquesTalk2 and AquesTalk10 are universal.
if(NOT CMAKE_OSX_ARCHITECTURES)
    set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "AquesTalk1 macOS libraries are arm64-only" FORCE)
endif()
if(NOT CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
    message(FATAL_ERROR "AquesTalk1 macOS libraries are arm64-only (CMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}).")
endif()

set(AQTK_RPATH "@loader_path")
set(AQTK1_LIBDIR "${AQTK_ROOT}/tk1/aqtk1_mac/lib")
set(AQTK2_LIB "${AQTK_ROOT}/tk2/aqtk2_mac/lib/libAquesTalk2Eva.dylib")
set(AQTK2_STAGED "libAquesTalk2Eva.dylib")
set(AQTK10_LIB "${AQTK_ROOT}/tk10/aqtk10_mac/lib/libAquesTalk10.dylib")
set(AQTK10_STAGED "libAquesTalk10.dylib")
set(AQTK2_PHONTDIR "${AQTK_ROOT}/tk2/aqtk2_mac/phont")

set(AQTK1_SOURCES "")
set(AQTK1_STAGED "")
foreach(_voice IN LISTS AQTK1_VOICES)
    set(_name "libAquesTalk1-${_voice}.dylib")
    list(APPEND AQTK1_SOURCES "${AQTK1_LIBDIR}/${_name}")
    list(APPEND AQTK1_STAGED "${_name}")
endforeach()
aqtk_require_files(${AQTK1_SOURCES} "${AQTK2_LIB}" "${AQTK10_LIB}")
aqtk_collect_phonts()

include("${CMAKE_CURRENT_LIST_DIR}/unix.cmake")
