# Finds an installed NDK, then hands off to its CMake toolchain.
# ANDROID_ABI comes from the preset. FORCE_LOAD needs API 28.
if(NOT ANDROID_PLATFORM AND NOT ANDROID_NATIVE_API_LEVEL)
    set(ANDROID_PLATFORM android-28)
endif()

set(_aqtk_ndk "")
if(ANDROID_NDK)
    set(_aqtk_ndk "${ANDROID_NDK}")
else()
    foreach(_var ANDROID_NDK ANDROID_NDK_HOME ANDROID_NDK_ROOT)
        if(DEFINED ENV{${_var}} AND NOT "$ENV{${_var}}" STREQUAL "")
            set(_aqtk_ndk "$ENV{${_var}}")
            break()
        endif()
    endforeach()
endif()

if(NOT _aqtk_ndk)
    set(_aqtk_ndk_roots "")
    foreach(_var ANDROID_HOME ANDROID_SDK_ROOT)
        if(DEFINED ENV{${_var}} AND NOT "$ENV{${_var}}" STREQUAL "")
            list(APPEND _aqtk_ndk_roots "$ENV{${_var}}/ndk")
        endif()
    endforeach()
    if(DEFINED ENV{LOCALAPPDATA} AND NOT "$ENV{LOCALAPPDATA}" STREQUAL "")
        list(APPEND _aqtk_ndk_roots "$ENV{LOCALAPPDATA}/Android/Sdk/ndk")
    endif()

    set(_aqtk_ndk_candidates "")
    foreach(_root IN LISTS _aqtk_ndk_roots)
        if(NOT IS_DIRECTORY "${_root}")
            continue()
        endif()
        file(GLOB _versions LIST_DIRECTORIES true "${_root}/*")
        foreach(_version IN LISTS _versions)
            if(EXISTS "${_version}/build/cmake/android.toolchain.cmake")
                list(APPEND _aqtk_ndk_candidates "${_version}")
            endif()
        endforeach()
    endforeach()
    if(_aqtk_ndk_candidates)
        list(SORT _aqtk_ndk_candidates COMPARE NATURAL ORDER DESCENDING)
        list(GET _aqtk_ndk_candidates 0 _aqtk_ndk)
    endif()
endif()

file(TO_CMAKE_PATH "${_aqtk_ndk}" _aqtk_ndk)
if(NOT EXISTS "${_aqtk_ndk}/build/cmake/android.toolchain.cmake")
    message(FATAL_ERROR
        "Android NDK not found. Set ANDROID_NDK_HOME, or install an NDK under ANDROID_HOME/ndk.")
endif()

set(ANDROID_NDK "${_aqtk_ndk}")
include("${_aqtk_ndk}/build/cmake/android.toolchain.cmake")
