function(aqtk_require_files)
    foreach(_path IN LISTS ARGN)
        if(NOT EXISTS "${_path}")
            message(FATAL_ERROR "Missing AquesTalk SDK file: ${_path}")
        endif()
    endforeach()
endfunction()

# Pass REQUIRED to fail when a phont is absent. Otherwise it is skipped.
function(aqtk_collect_phonts)
    set(_required FALSE)
    if(ARGC GREATER 0 AND ARGV0 STREQUAL "REQUIRED")
        set(_required TRUE)
    endif()

    set(_present "")
    foreach(_phont IN LISTS AQTK2_PHONTS)
        set(_aqtk2_phont "${AQTK2_PHONTDIR}/${_phont}.phont")
        if(EXISTS "${_aqtk2_phont}")
            list(APPEND _present "${_phont}")
        elseif(_required)
            message(FATAL_ERROR "Missing AquesTalk SDK file: ${_aqtk2_phont}")
        else()
            message(STATUS "AquesTalk2 phont not in the SDK, skipping: ${_phont}")
        endif()
    endforeach()
    set(AQTK2_PHONTS_PRESENT "${_present}" PARENT_SCOPE)
endfunction()
